In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5]

In [4]:
np.array(l)

array([1, 2, 3, 4, 5])

In [5]:
np.array([[1,2],[3,5]])

array([[1, 2],
       [3, 5]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [9]:
np.array(l)

array([1, 2, 3, 4, 5])

In [10]:
b = np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4, 5]])

In [13]:
b.dtype

dtype('int64')

In [14]:
l = [3,45,5,67,0,44,7]

In [55]:
l

[1, 2, 3, 4, 5, 66]

In [16]:
l

[3, 45, 5, 67, 0, 44, 7]

In [17]:
c = [3,45,5,67,0,44,7]

In [18]:
c

[3, 45, 5, 67, 0, 44, 7]

In [19]:
c[0]

3

In [20]:
c[4]

0

In [22]:
c[1]

45

In [23]:
b = np.copy(c)

In [24]:
b

array([ 3, 45,  5, 67,  0, 44,  7])

In [25]:
c

[3, 45, 5, 67, 0, 44, 7]

In [26]:
np.fromfunction(lambda i,j : i == j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j : i != j ,(3,3))

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [32]:
np.fromfunction(lambda i,j : i != j ,(4,9))

array([[False,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True]])

In [39]:
iterable = (i*i for i in range(5))

In [40]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [46]:
np.fromstring('234 567 567', sep = ' ')

array([234., 567., 567.])

In [47]:
l = [1,2,3,4,5,66]

In [48]:
ar = np.array(l)

In [49]:
ar

array([ 1,  2,  3,  4,  5, 66])

In [50]:
ar.ndim

1

In [51]:
b.ndim

1

In [54]:
b.ndim

1

In [56]:
p = [3,45,55,33,22,2,1]

In [57]:
np.array(p)

array([ 3, 45, 55, 33, 22,  2,  1])

In [58]:
np.size(p)

7

In [63]:
np.shape(p)

(7,)

In [74]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [76]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [88]:
n = np.ones((3,4))

In [91]:
n

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [92]:
p = np.zeros((3,4))

In [93]:
p

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
np.empty((4,6))

array([[0., 0., 0., 0., 1., 1.],
       [1., 1., 2., 2., 2., 2.],
       [0., 1., 2., 3., 0., 1.],
       [2., 3., 0., 1., 2., 3.]])

In [97]:
np.empty((3,3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [98]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [99]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
np.eye(11)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [103]:
np.linspace(2,3,20)

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [104]:
np.logspace(2,4,20)

array([  100.        ,   127.42749857,   162.37767392,   206.91380811,
         263.66508987,   335.98182863,   428.13323987,   545.55947812,
         695.19279618,   885.86679041,  1128.83789168,  1438.44988829,
        1832.98071083,  2335.72146909,  2976.35144163,  3792.69019073,
        4832.93023857,  6158.48211066,  7847.59970351, 10000.        ])

In [105]:
np.random.rand(3,4)

array([[0.9200273 , 0.77774287, 0.65472041, 0.00670102],
       [0.80936795, 0.74444458, 0.81013162, 0.31586757],
       [0.2225347 , 0.20887593, 0.38674532, 0.87326481]])

In [106]:
np.random.rand(3,4)

array([[0.45388024, 0.00606891, 0.19891583, 0.31276466, 0.96265658,
        0.35919391, 0.57814868, 0.63790527, 0.66111812],
       [0.09986229, 0.87585698, 0.46737338, 0.64188404, 0.46169757,
        0.4783737 , 0.62984374, 0.13601918, 0.98959374],
       [0.77699405, 0.3873411 , 0.9395164 , 0.78533075, 0.17402202,
        0.77443234, 0.46583679, 0.36278587, 0.18584419],
       [0.219106  , 0.21951804, 0.4507615 , 0.26419419, 0.91300646,
        0.29792434, 0.09182059, 0.35196266, 0.27771407]])